packages:
  # - { name: alfred, state: present }
  # - { name: iterm2, state: present }
  - { name: google-japanese-ime, state: present }
  # - { name: google-chrome, state: present }
  - { name: chromedriver, state: present }
  # - { name: firefox, state: present }
  # - { name: visual-studio-code, state: present }
  # - { name: coteditor, state: present }
  # - { name: vagrant, state: present }
  # - { name: virtualbox, state: present }
  # - { name: slack, state: present }
  - { name: postman, state: present }
  # - { name: teamsql, state: present }
  # - { name: font-ricty-diminished, state: present }
  - { name: ngrok, state: present }
  # - { name: discord, state: present }
  # - { name: docker, state: present }
  # - { name: zoom, state: present }
  