- block:
  - name: npm install with specific version
    community.general.npm:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: "{{ item.state }}"
      executable: "{{ npm_path }}"
      global: yes
    with_items: "{{ packages }}"
    when: item.version != None
  
  - name: npm install with latest version
    community.general.npm:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
      executable: "{{ npm_path }}"
      global: yes
    with_items: "{{ packages }}"
    when: item.version == None
  
  tags:
    - npm